import type { LevelDef, WaveDef } from './types.ts'
import { gridLevel } from './mapGrid.ts'
import { registerBoards } from './levels.ts'
import './frontierScenery.ts'

/**
 * The Frontier: ten boards beyond the campaign's road.
 *
 * The campaign is a staircase - each chapter a little harder than the last,
 * each unlocked by the one before. These are not steps on it. Every Frontier
 * board is open from the start and says plainly how hard it is, the way a
 * map select in Bloons sorts beginner boards from expert ones, so a player
 * can pick a gentle spiral on a slow evening or a four-gate storm when they
 * want to be punished.
 *
 * They are also where the ground itself gets to change shape. Boards here
 * are drawn rather than rect-listed (see mapGrid.ts), so they can be round,
 * ringed or broken into islands; roads climb onto terraces, cross the sky on
 * bridges and ramp between asteroids; and every one sits under its own sky.
 *
 * Their stars are their own. The Armory is priced against the campaign, and
 * letting ten more boards pay into it would buy the whole board outright.
 */

const g = (enemy: string, count: number, interval: number, delay = 0, lane = 0) =>
  ({ enemy, count, interval, delay, lane })

/** every Frontier board's drawing, kept so a test can hold the drawn roads to the lanes */
export const FRONTIER_GRIDS: Record<string, { rows: readonly string[], heights: Readonly<Record<string, number>> }> = {}

const grid = (id: string, rows: readonly string[], heights: Readonly<Record<string, number>> = {}) => {
  FRONTIER_GRIDS[id] = { rows, heights }
  return gridLevel(rows, heights)
}

/** the same column from several gates, each `stagger` seconds behind the last */
const gates = (lanes: number[], enemy: string, count: number, interval: number, delay = 0, stagger = 1.5) =>
  lanes.map((lane, i) => g(enemy, count, interval, delay + i * stagger, lane))

// ---------------------------------------------------------------- easy

const lanternbloomWaves: WaveDef[] = [
  { groups: [g('husk', 8, 1.5)] },
  { groups: [g('husk', 11, 1.2), g('sprinter', 4, 1.3, 8)] },
  { groups: [g('sprinter', 9, 1.0), g('husk', 8, 1.2, 5)] },
  { groups: [g('shield', 5, 2.0), g('husk', 9, 1.1, 4)] },
  { groups: [g('gargoyle', 5, 1.6), g('husk', 8, 1.1, 3), g('shardback', 1, 1, 8)] },
  { surge: true, groups: [g('husk', 14, 0.8), g('sprinter', 8, 0.9, 6)] },
  { groups: [g('acolyte', 4, 2.2), g('shield', 6, 1.8, 2), g('husk', 10, 1.0, 6)] },
  { groups: [g('spiderling', 16, 0.45), g('gargoyle', 6, 1.4, 5)] },
  { groups: [g('brute', 1, 1, 2), g('shield', 8, 1.6), g('sprinter', 12, 0.9, 5), g('shardback', 2, 5, 8)] },
  { surge: true, groups: [g('gargoyle', 10, 1.2), g('husk', 18, 0.75, 3), g('acolyte', 4, 2.0, 8)] },
  { groups: [g('brute', 2, 6, 3), g('shield', 8, 1.5), g('sprinter', 10, 0.9, 6)] },
  { groups: [g('spiderling', 20, 0.4), g('broodmother', 2, 8, 5), g('gargoyle', 8, 1.2, 9)] },
  { surge: true, groups: [g('shield', 11, 1.4), g('acolyte', 5, 1.8, 4), g('husk', 20, 0.7, 8), g('shardback', 2, 5, 12)] },
  { groups: [g('brute', 3, 6), g('gargoyle', 12, 1.0, 3), g('sprinter', 14, 0.8, 7), g('warlock', 3, 2.4, 10)] },
  { groups: [g('hollowking', 1, 1, 6), g('brute', 2, 8, 2), g('husk', 18, 0.8), g('shield', 10, 1.3, 8), g('gargoyle', 10, 1.1, 12)], breakAfter: 30 },
]

export const lanternbloomLevel: LevelDef = {
  id: 'lanternbloom',
  name: 'Lanternbloom Terraces',
  subtitle: 'A spiral climb to a hilltop keep',
  theme: 'blossom',
  seed: 4417,
  frontier: { tier: 'easy', feature: 'The road spirals up three terraces' },
  ...grid('lanternbloom', [
    '#######.....###########',
    '#####.........#########',
    '###.............####..#',
    '##.............==%%===.',
    '##o.aaaAaaaaaaA=.###..#',
    '#...aaaaaaaAaaa=..#####',
    '#..======x===aa=.o#####',
    '...=AaabBbBb=aa=...####',
    '...=aaabbbbb=Aa=...####',
    '.o.=aA====bb=aax...####',
    '...=aa=bbbbb=aA=.o.####',
    '...xaa=bBbBb=aa=...####',
    '#o.=Aa=======aa=..#####',
    '#..=aaaAaaaaaAa=.o#####',
    '##.=aaaaaaAaaaa=.######',
    '##.======x======.######',
    '###....o....o...#######',
    '#####.........#########',
    '#######.....###########',
  ], { a: 0.35, b: 0.7 }),
  lanes: [
    [[21, 3], [15, 3], [15, 15], [3, 15], [3, 6], [6, 6, 0.35], [12, 6, 0.35], [12, 12, 0.35], [6, 12, 0.35], [6, 9, 0.35], [9, 9, 0.7]],
  ],
  landmarks: [[5, 2, 'pagoda'], [13, 2, 'greatTree']],
  waves: lanternbloomWaves,
  startGold: 290,
  startLives: 20,
  intro: 'Lanterns drift up from the terraces. The Veil climbs the spiral road toward the keep at the top - every tower on the slopes watches two turns of it.',
}

const dunewakeWaves: WaveDef[] = [
  { groups: [g('husk', 9, 1.5)] },
  { groups: [g('sprinter', 7, 1.2), g('husk', 6, 1.4, 6)] },
  { groups: [g('husk', 10, 1.1), g('shield', 3, 2.4, 5)] },
  { groups: [g('gargoyle', 5, 1.7), g('sprinter', 6, 1.1, 4)] },
  { groups: [g('shield', 3, 2.4), g('husk', 9, 1.1, 4)] },
  { surge: true, groups: [g('sprinter', 11, 0.85), g('gargoyle', 4, 1.6, 6)] },
  { groups: [g('acolyte', 3, 2.6), g('husk', 11, 0.95, 2), g('shield', 4, 2.0, 8)] },
  { groups: [g('spiderling', 14, 0.5), g('shardback', 2, 5, 6)] },
  { groups: [g('brute', 1, 1, 3), g('gargoyle', 7, 1.4), g('sprinter', 8, 1.0, 8)] },
  { surge: true, groups: [g('shield', 6, 1.8), g('acolyte', 2, 2.5, 4), g('husk', 12, 0.85, 7)] },
  { groups: [g('broodmother', 1, 1, 2), g('spiderling', 12, 0.5, 6), g('gargoyle', 8, 1.2, 9)] },
  { groups: [g('warlock', 2, 3.0), g('shield', 7, 1.7, 2), g('sprinter', 10, 0.85, 7), g('shardback', 2, 5, 10)] },
  { surge: true, groups: [g('brute', 2, 8), g('gargoyle', 9, 1.15, 3), g('husk', 14, 0.75, 8)] },
  { groups: [g('acolyte', 3, 2.3), g('shield', 6, 1.6, 3), g('spiderling', 12, 0.5, 8)] },
  { groups: [g('brute', 2, 6), g('warlock', 3, 2.6, 3), g('gargoyle', 10, 1.05, 7), g('shardback', 2, 5, 10)] },
  { groups: [g('hollowking', 1, 1, 8), g('shield', 9, 1.4), g('sprinter', 12, 0.85, 5), g('gargoyle', 9, 1.15, 12)], breakAfter: 30 },
]

export const dunewakeLevel: LevelDef = {
  id: 'dunewake',
  name: 'Dunewake Oasis',
  subtitle: 'One road around the last water',
  theme: 'desert',
  seed: 5209,
  frontier: { tier: 'easy', feature: 'The road crests a dune and circles the oasis' },
  ...grid('dunewake', [
    '###########......###########',
    '#######..aabBbbBbaa..#######',
    '#####....aabbbbbbaa....#####',
    '###......aAaaaaaaAa......###',
    '##....========x========...##',
    '#..o..=...............=....#',
    '#.....=.o..o..o..o..o.=.o..#',
    '===x===......~~~......=.....',
    '...........~~~~~~~....x.....',
    '....o.....w~~~~~~~w.o.=.....',
    '#.....=.o.~~~~~~~~~...=.o..#',
    '#.....=....~~~w~~~....=....#',
    '##.o..=.o...........o.=...##',
    '###...========x========.####',
    '#####.............o...######',
    '#######...o...o......#######',
    '###########......###########',
  ], { a: 0.6, b: 1.2 }),
  lanes: [
    [[0, 7], [6, 7], [6, 4], [9, 4], [12, 4, 0.6], [16, 4, 0.6], [19, 4], [22, 4], [22, 13], [6, 13], [6, 10]],
  ],
  landmarks: [[25, 6, 'pyramid'], [3, 3, 'monolith']],
  waves: dunewakeWaves,
  startGold: 350,
  startLives: 20,
  intro: 'The Veil walks the caravan road over the dune and all the way around the oasis. Towers on the shore watch both sides of the loop.',
}

const cloudstepWaves: WaveDef[] = [
  { groups: [g('husk', 8, 1.5)] },
  { groups: [g('gargoyle', 4, 1.8), g('husk', 7, 1.3, 5)] },
  { groups: [g('sprinter', 10, 1.0)] },
  { groups: [g('shield', 5, 2.0), g('gargoyle', 6, 1.5, 6)] },
  { groups: [g('husk', 13, 0.9), g('sprinter', 6, 1.0, 8), g('shardback', 1, 1, 10)] },
  { surge: true, groups: [g('gargoyle', 11, 1.1), g('husk', 9, 1.0, 5)] },
  { groups: [g('acolyte', 4, 2.3), g('shield', 7, 1.7, 3)] },
  { groups: [g('spiderling', 16, 0.45), g('gargoyle', 7, 1.3, 6), g('shardback', 2, 5, 8)] },
  { groups: [g('warlock', 4, 2.6), g('sprinter', 12, 0.85, 3), g('husk', 12, 0.85, 9)] },
  { surge: true, groups: [g('shield', 10, 1.4), g('gargoyle', 10, 1.1, 5), g('acolyte', 4, 2.1, 9)] },
  { groups: [g('brute', 2, 7, 2), g('spiderling', 18, 0.42, 4), g('gargoyle', 10, 1.1, 10)] },
  { groups: [g('hollowking', 1, 1, 5), g('husk', 14, 0.85), g('gargoyle', 10, 1.1, 9), g('shardback', 2, 5, 12)], breakAfter: 30 },
  { groups: [g('mistwalker', 6, 1.4), g('shield', 10, 1.4, 4), g('sprinter', 12, 0.85, 9)] },
  { surge: true, groups: [g('gargoyle', 16, 0.85), g('warlock', 5, 2.2, 5), g('husk', 16, 0.75, 9)] },
  { groups: [g('broodmother', 2, 8), g('acolyte', 6, 1.8, 4), g('gargoyle', 12, 1.0, 8)] },
  { groups: [g('brute', 3, 6), g('mistwalker', 8, 1.1, 3), g('shield', 12, 1.2, 8), g('shardback', 2, 5, 12)] },
  { surge: true, groups: [g('gargoyle', 18, 0.75), g('sprinter', 16, 0.65, 6), g('acolyte', 5, 1.9, 10)] },
  { groups: [g('hollowking', 1, 1, 10), g('brute', 3, 6), g('gargoyle', 16, 0.85, 4), g('warlock', 6, 1.9, 9), g('shield', 12, 1.1, 14)], breakAfter: 30 },
]

export const cloudstepLevel: LevelDef = {
  id: 'cloudstep',
  name: 'Cloudstep Isles',
  subtitle: 'Four islands and the bridges between',
  theme: 'skyreach',
  seed: 6143,
  frontier: { tier: 'easy', feature: 'Bridges climb and fall between floating islands' },
  ...grid('cloudstep', [
    '################################',
    '############bBbbBbb#############',
    '###########bbbbbbbbb############',
    '##########====x====bb###########',
    '##########=bbbbbbb=bb####....###',
    '###.....##=bBbbBbb=bB###......##',
    '##...===%%=bbbbbbb=b###.....o..#',
    '#..o.=..##bbBbbbBb=####.o......#',
    '#....=..##########%####........#',
    '#....=.o##########%####.o.=====#',
    '#..o.=..##########%####...=....#',
    '#....=..####=======aa##.o.x.o..#',
    '#==x==..###a=aAaaAaaA##...=....#',
    '#......o##Aa=aaaaaaaa##...=.o..#',
    '##..o..###aa===x=====%%====...##',
    '###...#####aaaAaaAaa###......###',
    '############aaaaaaa#############',
    '################################',
  ], { a: 0.5, b: 1.0 }),
  lanes: [
    [[1, 12], [5, 12], [5, 6], [7, 6], [10, 6, 1.0], [10, 3, 1.0], [18, 3, 1.0], [18, 7, 1.0], [18, 11, 0.5], [12, 11, 0.5], [12, 14, 0.5], [20, 14, 0.5], [23, 14], [26, 14], [26, 9], [30, 9]],
  ],
  landmarks: [[28, 4, 'windmill'], [2, 9, 'ruin']],
  waves: cloudstepWaves,
  startGold: 300,
  startLives: 20,
  intro: 'Nothing but sky between these islands. Bridges carry the road up to the high meadow and down again - and nobody builds on a bridge, so claim the ground at either end.',
}

// ---------------------------------------------------------------- medium

const coralspireWaves: WaveDef[] = [
  { groups: [g('husk', 6, 1.5), g('husk', 6, 1.5, 3, 1)] },
  { groups: [g('sprinter', 6, 1.2), g('shield', 3, 2.2, 4, 1)] },
  { groups: [g('shield', 4, 2.0), g('sprinter', 6, 1.1, 2, 1), g('husk', 5, 1.2, 8)] },
  { groups: [g('gargoyle', 4, 1.6, 0, 1), g('acolyte', 2, 2.6), g('husk', 8, 1.0, 5, 1)] },
  { groups: [g('mistwalker', 3, 1.6), g('shield', 4, 1.9, 3, 1), g('shardback', 2, 5, 7)] },
  { surge: true, groups: [g('spiderling', 12, 0.5, 0, 1), g('broodmother', 1, 1, 6), g('gargoyle', 4, 1.5, 8, 1)] },
  { groups: [g('warlock', 2, 2.8), g('mistwalker', 4, 1.4, 2, 1), g('sprinter', 7, 1.0, 6)] },
  { groups: [g('brute', 1, 1, 0, 1), g('shield', 6, 1.7), g('acolyte', 2, 2.4, 5, 1), g('shardback', 2, 5, 9, 1)] },
  { groups: [g('gargoyle', 7, 1.3), g('gargoyle', 6, 1.3, 3, 1), g('husk', 9, 0.9, 8)] },
  { groups: [g('hollowking', 1, 1, 6, 1), g('mistwalker', 4, 1.3), g('shield', 4, 1.7, 3, 1)], breakAfter: 30 },
  { groups: [g('hexling', 1, 1, 4), g('warlock', 3, 2.5, 0, 1), g('spiderling', 14, 0.45, 3), g('shardback', 2, 5, 9)] },
  { surge: true, groups: [g('broodmother', 2, 8, 0, 1), g('sprinter', 10, 0.85), g('acolyte', 3, 2.1, 6, 1)] },
  { groups: [g('brute', 2, 7), g('mistwalker', 7, 1.05, 2, 1), g('gargoyle', 7, 1.15, 6)] },
  { groups: [g('wardbearer', 1, 1, 2, 1), g('shield', 8, 1.4, 0, 1), g('warlock', 4, 2.2, 4), g('shardback', 2, 5, 10, 1)] },
  { surge: true, groups: [g('mistwalker', 8, 1.0), g('hexling', 1, 1, 3, 1), g('gargoyle', 9, 1.05, 6, 1)] },
  { groups: [g('brute', 2, 7, 0, 1), g('acolyte', 4, 2.0), g('sprinter', 12, 0.75, 5, 1), g('shardback', 2, 5, 10)] },
  { groups: [g('broodmother', 2, 8), g('spiderling', 16, 0.42, 4, 1), g('warlock', 4, 2.1, 8, 1)] },
  { groups: [g('juggernaut', 1, 1, 6), g('shield', 9, 1.3, 0, 1), g('gargoyle', 9, 1.05, 5)], breakAfter: 30 },
  { surge: true, groups: [g('mistwalker', 9, 0.95, 0, 1), g('wardbearer', 1, 1, 3), g('brute', 2, 6, 5), g('acolyte', 4, 1.9, 8, 1)] },
  { groups: [g('juggernaut', 1, 1, 8, 1), g('gargoyle', 10, 0.95), g('warlock', 5, 2.0, 6), g('shield', 9, 1.25, 12, 1)] },
]

export const coralspireLevel: LevelDef = {
  id: 'coralspire',
  name: 'Coralspire Atoll',
  subtitle: 'Around the reef, across the lagoon',
  theme: 'reef',
  seed: 7351,
  frontier: { tier: 'medium', feature: 'Two roads ring the atoll, then share one causeway' },
  ...grid('coralspire', [
    '##############################',
    '#####......o......o......#####',
    '###aa....................aa###',
    '##aa======================aa##',
    '##aA=a........x.........a=Aa##',
    '#..a=...o..o..=..o..o....=a..#',
    '#...=....~~~~~=~~~~~~....=...#',
    '#.o.=...~~~~~~=~~~~~~~...=.o.#',
    '#...=.o~~~w~~~=~~~w~~~~o.=...#',
    '#...=..~~~~~..=...~~~~~..=...#',
    '#...x..~~~~.o.=.o..~~~~..x...#',
    '#.o.=..~~~~...=....~~~~..=.o.#',
    '#...=.o~~~~.o...o..~~~~o.=...#',
    '#...=..~~w~~......~~w~~..=...#',
    '#.o.=...~~~~~~~~~~~~~~...=.o.#',
    '#...=....~~~~~~~~~~~~....=...#',
    '#..a=..o..o..####..o..o..=a..#',
    '##aA=a.......####.......a=Aa##',
    '##aa====x====####====x====aa##',
    '###aa........####........aa###',
    '#####.......######.......#####',
    '##############################',
  ], { a: 0.6 }),
  lanes: [
    [[12, 18], [4, 18], [4, 3], [14, 3], [14, 11]],
    [[17, 18], [25, 18], [25, 3], [14, 3], [14, 11]],
  ],
  landmarks: [[2, 9, 'coralSpire'], [27, 9, 'arch']],
  waves: coralspireWaves,
  startGold: 440,
  startLives: 20,
  startShards: 3,
  intro: 'The Veil wades ashore at the mouth of the atoll and splits around the reef. Both columns meet on the causeway to the keep - boats in the lagoon reach every part of it.',
}

const glimmerdeepWaves: WaveDef[] = [
  { groups: [g('husk', 7, 1.4), g('husk', 6, 1.4, 4, 1)] },
  { groups: [g('spiderling', 10, 0.6), g('sprinter', 5, 1.2, 3, 1)] },
  { groups: [g('mistwalker', 3, 1.8), g('husk', 8, 1.1, 2, 1)] },
  { groups: [g('shield', 5, 2.0, 0, 1), g('mistwalker', 4, 1.5, 4)] },
  { groups: [g('acolyte', 3, 2.4), g('spiderling', 12, 0.5, 2, 1), g('shardback', 2, 5, 6)] },
  { surge: true, groups: [g('mistwalker', 6, 1.3, 0, 1), g('gargoyle', 5, 1.5), g('husk', 8, 1.0, 6)] },
  { groups: [g('broodmother', 1, 1, 2), g('warlock', 3, 2.6, 0, 1), g('sprinter', 8, 1.0, 5)] },
  { groups: [g('hexling', 1, 1, 3, 1), g('shield', 8, 1.6), g('mistwalker', 7, 1.2, 5, 1), g('shardback', 2, 5, 9, 1)] },
  { groups: [g('spiderling', 21, 0.4), g('spiderling', 16, 0.45, 3, 1), g('acolyte', 5, 2.2, 8)] },
  { surge: true, groups: [g('brute', 1, 1, 0, 1), g('mistwalker', 9, 1.1), g('warlock', 5, 2.3, 5, 1)] },
  { groups: [g('gargoyle', 9, 1.2, 0, 1), g('shield', 9, 1.5), g('hexling', 2, 5, 6)] },
  { groups: [g('hollowking', 1, 1, 6), g('broodmother', 2, 8, 0, 1), g('mistwalker', 7, 1.1, 4)], breakAfter: 30 },
  { groups: [g('wardbearer', 1, 1, 2, 1), g('shield', 10, 1.4, 0, 1), g('warlock', 6, 2.1, 3), g('shardback', 2, 5, 10)] },
  { surge: true, groups: [g('mistwalker', 12, 0.95), g('spiderling', 18, 0.45, 3, 1), g('brute', 1, 1, 8)] },
  { groups: [g('hexling', 2, 6, 0, 1), g('acolyte', 6, 2.0), g('sprinter', 16, 0.75, 5, 1), g('shardback', 2, 5, 10, 1)] },
  { groups: [g('broodmother', 2, 8), g('brute', 2, 7, 3, 1), g('gargoyle', 12, 1.1, 6)] },
  { surge: true, groups: [g('mistwalker', 12, 0.9, 0, 1), g('warlock', 7, 1.9), g('shield', 12, 1.3, 6, 1)] },
  { groups: [g('juggernaut', 1, 1, 6, 1), g('mistwalker', 9, 1.0), g('acolyte', 6, 1.9, 5)], breakAfter: 30 },
  { groups: [g('wardbearer', 2, 9), g('spiderling', 23, 0.4, 3, 1), g('hexling', 2, 6, 6), g('shardback', 2, 5, 12, 1)] },
  { surge: true, groups: [g('brute', 3, 6, 0, 1), g('mistwalker', 14, 0.85), g('gargoyle', 12, 1.0, 6, 1)] },
  { groups: [g('broodmother', 3, 7), g('warlock', 8, 1.8, 3, 1), g('shield', 14, 1.2, 8)] },
  { groups: [g('juggernaut', 1, 1, 4), g('juggernaut', 1, 1, 12, 1), g('mistwalker', 14, 0.85, 0, 1), g('hexling', 3, 5, 6), g('acolyte', 7, 1.8, 10, 1)] },
]

export const glimmerdeepLevel: LevelDef = {
  id: 'glimmerdeep',
  name: 'Glimmerdeep Hollow',
  subtitle: 'A crystal bridge over the dark',
  theme: 'cavern',
  seed: 8077,
  frontier: { tier: 'medium', feature: 'Roads climb two shelves to a bridge over a chasm' },
  ...grid('glimmerdeep', [
    '###.......................###',
    '#..........o................#',
    '#===x====.....c..o..........#',
    '....o...=....................',
    '........=.o.............c....',
    '...c....=....##..............',
    '......bb=b..####..bbb....~...',
    '.~~..bBb=bB######bBbbB..~w~..',
    '.~w..bbb=bb######bbbbb...~...',
    '.~~..bBb===%%%%%%======......',
    '.~~..bbb=bb######bbbbb=.o....',
    '.....bBb=bB######bBbbB=......',
    '...c..bb=b..####..bbb.x..c...',
    '........=....##..o..o.=......',
    '....o...=..o..........=.o....',
    '#===x====.....c.......===x==#',
    '#..........o.......o......o.#',
    '###.......................###',
  ], { b: 1.4, c: 2.0 }),
  lanes: [
    [[1, 2], [8, 2], [8, 5], [8, 8, 1.4], [8, 9, 1.4], [19, 9, 1.4], [22, 9], [22, 15], [27, 15]],
    [[1, 15], [8, 15], [8, 12, 1.4], [8, 9, 1.4], [19, 9, 1.4], [22, 9], [22, 15], [27, 15]],
  ],
  landmarks: [[26, 3, 'crystalSpire'], [2, 13, 'crystalSpire']],
  waves: glimmerdeepWaves,
  startGold: 390,
  startLives: 20,
  startShards: 4,
  intro: 'Mistwalkers love the dark. Both tunnels climb onto the shelves and cross the chasm on a single crystal span - the shelves see everything, the cavern floor sees only what walks past it.',
}

const starfallWaves: WaveDef[] = [
  { groups: [g('husk', 7, 1.4), g('husk', 6, 1.4, 3, 1)] },
  { groups: [g('gargoyle', 4, 1.6), g('sprinter', 6, 1.2, 2, 1)] },
  { groups: [g('shield', 4, 2.0, 0, 1), g('gargoyle', 5, 1.5, 4)] },
  { groups: [g('riftwing', 2, 2.2), g('husk', 10, 1.0, 2, 1)] },
  { groups: [g('acolyte', 3, 2.4, 0, 1), g('mistwalker', 4, 1.5), g('shardback', 2, 5, 6, 1)] },
  { surge: true, groups: [g('gargoyle', 8, 1.2), g('gargoyle', 6, 1.3, 3, 1), g('riftwing', 2, 2.0, 7)] },
  { groups: [g('warlock', 3, 2.6), g('shield', 6, 1.7, 2, 1), g('sprinter', 8, 1.0, 6)] },
  { groups: [g('spiderling', 16, 0.5, 0, 1), g('broodmother', 1, 1, 5), g('riftwing', 3, 1.8, 8, 1)] },
  { groups: [g('mistwalker', 8, 1.2), g('gargoyle', 9, 1.2, 3, 1), g('shardback', 2, 5, 8)] },
  { surge: true, groups: [g('riftwing', 6, 1.5, 0, 1), g('shield', 9, 1.5), g('acolyte', 5, 2.2, 6, 1)] },
  { groups: [g('hollowking', 1, 1, 5, 1), g('gargoyle', 12, 1.1), g('sprinter', 12, 0.9, 6, 1)], breakAfter: 30 },
  { groups: [g('wardbearer', 1, 1, 3), g('mistwalker', 9, 1.1, 0, 1), g('warlock', 5, 2.3, 5), g('shardback', 2, 5, 10, 1)] },
  { groups: [g('riftwing', 7, 1.4), g('hexling', 1, 1, 4, 1), g('shield', 9, 1.4, 6, 1)] },
  { surge: true, groups: [g('brute', 2, 7, 0, 1), g('gargoyle', 14, 1.0), g('acolyte', 6, 2.0, 6, 1)] },
  { groups: [g('broodmother', 2, 8), g('riftwing', 6, 1.4, 3, 1), g('spiderling', 18, 0.45, 6, 1)] },
  { groups: [g('mistwalker', 12, 0.95, 0, 1), g('warlock', 6, 2.1), g('gargoyle', 12, 1.0, 5, 1), g('shardback', 2, 5, 10)] },
  { surge: true, groups: [g('riftwing', 9, 1.2), g('riftwing', 7, 1.3, 4, 1), g('shield', 12, 1.3, 8)] },
  { groups: [g('juggernaut', 1, 1, 6), g('gargoyle', 14, 0.9, 0, 1), g('hexling', 2, 6, 4)], breakAfter: 30 },
  { groups: [g('wardbearer', 2, 9, 0, 1), g('mistwalker', 14, 0.85), g('acolyte', 6, 1.9, 6, 1), g('shardback', 2, 5, 12)] },
  { surge: true, groups: [g('riftwing', 12, 1.0, 0, 1), g('brute', 2, 6), g('gargoyle', 14, 0.9, 5)] },
  { groups: [g('broodmother', 3, 7, 0, 1), g('warlock', 7, 1.9), g('riftwing', 7, 1.2, 8, 1), g('shield', 12, 1.2, 10)] },
  { groups: [g('veilqueen', 1, 1, 6), g('riftwing', 9, 1.1, 0, 1), g('gargoyle', 16, 0.8, 3), g('mistwalker', 12, 0.9, 9, 1)], breakAfter: 30 },
]

export const starfallLevel: LevelDef = {
  id: 'starfall',
  name: 'Starfall Drift',
  subtitle: 'Asteroids strung together with light',
  theme: 'cosmos',
  seed: 9433,
  frontier: { tier: 'medium', feature: 'Light bridges ramp between asteroids at four heights' },
  ...grid('starfall', [
    '################################',
    '##.....######cccc###############',
    '#..o....####ccCcCc##############',
    '#.....o.#####cccc########aaaa###',
    '#.=x==..################aaAaaa##',
    '#....=..####bbbbbbb####aaaaaaaa#',
    '#..o.===%%%=====bbbb###a=====aa#',
    '##....o####bbBb=bBbb###a=aaa=aa#',
    '###########bbbb=bbbb###a=aAa=aa#',
    '###########bBbb=====%%%==aaa=aa#',
    '###########bbbb=bbbb###aaaaaxaA#',
    '###########bbBbxbBbb###AaaAa=aa#',
    '##aaaaa####bbbb=bbbb###aaaaa=aa#',
    '#aaAa===%%%=====bBbb###aa====aa#',
    '#aaaa=aA####bbbbbbb####aaaaaaaa#',
    '#a=x==aa################aaAaaa##',
    '#aaaaaAa####aaaa#########aaaa###',
    '#aaAaaaa###aaAAaa###############',
    '##aaaaa#####aaaa################',
    '################################',
  ], { a: 0.6, b: 1.2, c: 1.8 }),
  lanes: [
    [[2, 4], [5, 4], [5, 6], [11, 6, 1.2], [15, 6, 1.2], [15, 9, 1.2], [19, 9, 1.2], [24, 9, 0.6], [24, 6, 0.6], [28, 6, 0.6], [28, 13, 0.6], [25, 13, 0.6]],
    [[2, 15, 0.6], [5, 15, 0.6], [5, 13, 0.6], [11, 13, 1.2], [15, 13, 1.2], [15, 9, 1.2], [19, 9, 1.2], [24, 9, 0.6], [24, 6, 0.6], [28, 6, 0.6], [28, 13, 0.6], [25, 13, 0.6]],
  ],
  landmarks: [[29, 4, 'observatory'], [2, 17, 'monolith']],
  waves: starfallWaves,
  startGold: 420,
  startLives: 20,
  startShards: 4,
  intro: 'Out past the last star, the Veil hops between drifting rocks on bridges of light. Whatever flies ignores the bridges - and plenty here flies.',
}

const serpentWaves: WaveDef[] = [
  { groups: [g('husk', 8, 1.4), g('husk', 5, 1.5, 6, 1)] },
  { groups: [g('shield', 4, 2.2), g('sprinter', 6, 1.2, 3, 1)] },
  { groups: [g('husk', 10, 1.0, 0, 1), g('acolyte', 3, 2.4)] },
  { groups: [g('gargoyle', 6, 1.4), g('shield', 5, 2.0, 3, 1)] },
  { surge: true, groups: [g('sprinter', 12, 0.8), g('husk', 10, 0.9, 2, 1), g('shardback', 2, 5, 8)] },
  { groups: [g('brute', 1, 1, 0, 1), g('acolyte', 4, 2.2), g('shield', 6, 1.7, 4)] },
  { groups: [g('spiderling', 14, 0.5), g('broodmother', 1, 1, 4, 1), g('gargoyle', 5, 1.5, 6)] },
  { groups: [g('warlock', 5, 2.4, 0, 1), g('shield', 9, 1.5), g('shardback', 2, 5, 9, 1)] },
  { surge: true, groups: [g('brute', 2, 8), g('acolyte', 6, 2.0, 3, 1), g('husk', 16, 0.8, 6)] },
  { groups: [g('mistwalker', 8, 1.2, 0, 1), g('hexling', 1, 1, 4), g('sprinter', 12, 0.9, 6)] },
  { groups: [g('wardbearer', 1, 1, 2), g('shield', 12, 1.3), g('gargoyle', 9, 1.2, 4, 1), g('shardback', 2, 5, 10)] },
  { groups: [g('hollowking', 1, 1, 6, 1), g('brute', 2, 7), g('acolyte', 6, 2.0, 5)], breakAfter: 30 },
  { surge: true, groups: [g('spiderling', 21, 0.4, 0, 1), g('broodmother', 2, 8), g('warlock', 5, 2.2, 6, 1)] },
  { groups: [g('shield', 14, 1.2), g('hexling', 2, 6, 3, 1), g('mistwalker', 9, 1.0, 6)] },
  { groups: [g('brute', 3, 6, 0, 1), g('acolyte', 7, 1.8), g('gargoyle', 12, 1.0, 6), g('shardback', 2, 5, 12, 1)] },
  { groups: [g('juggernaut', 1, 1, 5), g('shield', 12, 1.3, 0, 1), g('warlock', 6, 2.0, 6)], breakAfter: 30 },
  { surge: true, groups: [g('wardbearer', 2, 8, 0, 1), g('sprinter', 18, 0.7), g('acolyte', 6, 1.9, 6, 1)] },
  { groups: [g('mistwalker', 12, 0.9), g('brute', 2, 6, 3, 1), g('gargoyle', 14, 0.9, 6)] },
  { groups: [g('broodmother', 3, 7, 0, 1), g('hexling', 3, 5, 4), g('shield', 14, 1.1, 8), g('shardback', 2, 5, 12)] },
  { surge: true, groups: [g('brute', 5, 5), g('warlock', 7, 1.8, 3, 1), g('mistwalker', 12, 0.9, 7)] },
  { groups: [g('juggernaut', 1, 1, 4, 1), g('wardbearer', 2, 8), g('acolyte', 7, 1.7, 5, 1), g('gargoyle', 14, 0.9, 8)] },
  { groups: [g('shield', 16, 1.0, 0, 1), g('hexling', 3, 5, 3), g('brute', 3, 6, 6), g('shardback', 3, 4, 10, 1)] },
  { surge: true, groups: [g('mistwalker', 14, 0.8), g('warlock', 8, 1.7, 3, 1), g('gargoyle', 16, 0.8, 6), g('acolyte', 6, 1.8, 10, 1)] },
  { groups: [g('juggernaut', 1, 1, 4), g('juggernaut', 1, 1, 10, 1), g('hollowking', 1, 1, 16), g('brute', 3, 5, 0, 1), g('shield', 16, 1.0, 6), g('acolyte', 7, 1.6, 12, 1)] },
]

export const serpentLevel: LevelDef = {
  id: 'serpentstair',
  name: 'The Serpent Stair',
  subtitle: 'Up the temple and down again',
  theme: 'jungle',
  seed: 3187,
  frontier: { tier: 'medium', feature: 'Both roads climb a four-tier temple to its summit' },
  ...grid('serpentstair', [
    '###.......................###',
    '#.............=..........=..#',
    '#..........o..=..o.......=..#',
    '.~....aaaaaaaa=aaaaaaaa..=...',
    '.~....aaAaaaaa=aaaaaAaa..=...',
    '.~....aabbbbbb=bbbbbbaa.o=...',
    '.~...oaabbbBbb=bbBbbbaa..x...',
    '.~....aAbbcccc=ccccbbAa..=...',
    '.~....aabbCccc=cccCbbaa..=...',
    '.~....aabbccDd=ddccbbaa..=...',
    '.~.=======================...',
    '.~.=..aabbccddddDccbbaa......',
    '.w.=..aabBccCcccCccBbaa......',
    '.~.=..aAbbcccccccccbbAa......',
    '.~.=..aabbbbBbbbBbbbbaa......',
    '.~.x.oaabbbbbbbbbbbbbaa.o....',
    '.~.=..aaaaAaaaaaaaAaaaa......',
    '.~.=..aaaaaaaaaaaaaaaaa......',
    '.~~=~~~~~~~~~~~~~~~~w~~~~~~~.',
    '#~~=~~~~w~~~~~~~~~~~~~~~~~~~#',
    '#..===========x=============#',
    '###.......o.......o.......###',
  ], { a: 0.5, b: 1.0, c: 1.5, d: 2.0 }),
  lanes: [
    [[27, 20], [3, 20], [3, 10], [5, 10], [7, 10, 0.5], [9, 10, 1.0], [11, 10, 1.5], [13, 10, 2.0], [14, 10, 2.0], [14, 8, 1.5], [14, 6, 1.0], [14, 4, 0.5], [14, 2], [14, 1]],
    [[25, 1], [25, 10], [23, 10], [21, 10, 0.5], [19, 10, 1.0], [17, 10, 1.5], [15, 10, 2.0], [14, 10, 2.0], [14, 8, 1.5], [14, 6, 1.0], [14, 4, 0.5], [14, 2], [14, 1]],
  ],
  landmarks: [[26, 15, 'serpentIdol'], [5, 2, 'ruin']],
  waves: serpentWaves,
  startGold: 440,
  startLives: 20,
  startShards: 4,
  intro: 'The long column wades the moat and climbs the west stair; the short one comes straight down the jungle road to the east stair. They meet at the summit and descend together to your keep.',
}

// ---------------------------------------------------------------- hard

const rimeveilWaves: WaveDef[] = [
  { groups: gates([0, 1, 2], 'husk', 4, 1.5, 0, 2) },
  { groups: [...gates([0, 2], 'sprinter', 5, 1.2, 0, 2), g('shield', 3, 2.2, 3, 1)] },
  { groups: [...gates([0, 1, 2], 'shield', 2, 2.2, 0, 2), g('gargoyle', 3, 1.6, 6, 1)] },
  { groups: [g('mistwalker', 3, 1.6, 0, 1), g('acolyte', 2, 2.4, 2, 2), g('husk', 8, 1.0, 4)] },
  { surge: true, groups: [...gates([0, 1, 2], 'gargoyle', 3, 1.4, 0, 2), g('shardback', 2, 5, 8, 1)] },
  { groups: [g('riftwing', 2, 2.0, 0, 2), g('spiderling', 12, 0.55), g('broodmother', 1, 1, 5, 1)] },
  { groups: [...gates([0, 1, 2], 'mistwalker', 2, 1.6, 0, 2), g('warlock', 2, 2.6, 6, 1)] },
  { groups: [g('brute', 1, 1, 0, 2), g('shield', 6, 1.6, 2), g('acolyte', 3, 2.2, 4, 1), g('shardback', 2, 5, 10)] },
  { surge: true, groups: [...gates([0, 2], 'riftwing', 2, 1.8, 0, 3), g('sprinter', 7, 0.9, 5, 1)] },
  { groups: [g('hexling', 1, 1, 2, 1), ...gates([0, 1, 2], 'shield', 4, 1.6, 0, 2), g('warlock', 3, 2.4, 8, 2)] },
  { groups: [g('broodmother', 1, 1, 0, 1), g('gargoyle', 8, 1.2, 2), g('mistwalker', 6, 1.2, 4, 2)] },
  { groups: [g('hollowking', 1, 1, 6, 1), ...gates([0, 2], 'acolyte', 3, 2.2, 0, 3), g('shardback', 2, 5, 10, 1)], breakAfter: 30 },
  { surge: true, groups: [g('riftherald', 1, 1, 2, 2), g('brute', 2, 7), g('riftwing', 4, 1.5, 4, 1)] },
  { groups: [...gates([0, 1, 2], 'mistwalker', 5, 1.1, 0, 2), g('wardbearer', 1, 1, 6, 1)] },
  { groups: [g('warlock', 5, 2.0, 0, 2), g('spiderling', 16, 0.42, 3), g('hexling', 2, 6, 5, 1), g('shardback', 2, 5, 12, 2)] },
  { surge: true, groups: [...gates([0, 1, 2], 'gargoyle', 6, 1.05, 0, 2), g('riftwing', 4, 1.4, 8, 1)] },
  { groups: [g('brute', 2, 6, 0, 1), g('broodmother', 2, 8, 2, 2), g('shield', 10, 1.3, 4), g('acolyte', 3, 2.1, 8, 1)] },
  { groups: [g('veilqueen', 1, 1, 6, 1), ...gates([0, 2], 'mistwalker', 5, 1.1, 0, 3)], breakAfter: 30 },
  { surge: true, groups: [g('riftherald', 2, 9, 0, 1), g('warlock', 5, 1.9, 2, 2), g('sprinter', 14, 0.7, 5), g('shardback', 2, 5, 12, 1)] },
  { groups: [...gates([0, 1, 2], 'riftwing', 3, 1.3, 0, 2), g('wardbearer', 2, 8, 6, 2)] },
  { groups: [g('juggernaut', 1, 1, 6, 1), g('hexling', 2, 6, 0, 2), g('shield', 10, 1.2, 3), g('acolyte', 4, 1.9, 8, 1)], breakAfter: 30 },
  { surge: true, groups: [...gates([0, 1, 2], 'mistwalker', 7, 0.9, 0, 2), g('brute', 2, 7, 6, 1)] },
  { groups: [g('broodmother', 2, 8, 0, 2), g('riftherald', 2, 8, 3), g('gargoyle', 12, 0.85, 5, 1), g('shardback', 3, 4, 10, 2)] },
  { groups: [...gates([0, 1, 2], 'warlock', 3, 1.8, 0, 2), g('wardbearer', 2, 8, 4, 1), g('riftwing', 6, 1.2, 8, 2)] },
  { surge: true, groups: [g('brute', 3, 6, 0, 1), ...gates([0, 2], 'mistwalker', 8, 0.85, 2, 3), g('hexling', 2, 6, 8, 1)] },
  { groups: [g('veilqueen', 1, 1, 4, 1), g('juggernaut', 1, 1, 12), ...gates([0, 1, 2], 'riftwing', 4, 1.1, 0, 3), g('shield', 12, 1.05, 8, 1)] },
]

export const rimeveilLevel: LevelDef = {
  id: 'rimeveil',
  name: 'Rimeveil Glacier',
  subtitle: 'Three roads and two crevasses',
  theme: 'aurora',
  hazard: 'deepchill',
  seed: 2269,
  frontier: { tier: 'hard', feature: 'Ice bridges span two crevasses under the aurora' },
  ...grid('rimeveil', [
    '##..=...........=.........=.##',
    '#...=...........=.........=..#',
    '..o.=....o......=..~~~.o..=...',
    '....x..o....o...x..~w~....x...',
    '....=...........=.........=.o.',
    '....=..##....#..=....##...=...',
    '####%###########%#########%###',
    '####%###########%#########%###',
    '##aa=aa#Aaaaa#aa=aaaaaa#aa=a##',
    'aaaa=aaaaa=======Aaaaaaaaa=aaa',
    'aaaa===x===aaaAaaaaa===x===aaa',
    'aaAaaaaaaa=abbaaaaaa=aaaAaaAaa',
    'aaaaaaaAaa=abbaaaAaa=aaAaaaaaa',
    'aaaaaa#aaa=aaaa##aaa=aaaa#aaaa',
    '##########%#########%#########',
    '##########%#########%#########',
    '#....#....=...##..o.=.......##',
    '.........o=.o.......=...o.....',
    '.....bb...==x========.bbb.....',
    '.....bb......o.=......bbb..o..',
    '#..o...........=.o...........#',
    '##..........................##',
  ], { a: 0.8, b: 1.6 }),
  lanes: [
    [[4, 0], [4, 5], [4, 8, 0.8], [4, 10, 0.8], [10, 10, 0.8], [10, 13, 0.8], [10, 16], [10, 18], [15, 18], [15, 20]],
    [[16, 0], [16, 5], [16, 8, 0.8], [16, 9, 0.8], [10, 9, 0.8], [10, 10, 0.8], [10, 13, 0.8], [10, 16], [10, 18], [15, 18], [15, 20]],
    [[26, 0], [26, 5], [26, 8, 0.8], [26, 10, 0.8], [20, 10, 0.8], [20, 13, 0.8], [20, 16], [20, 18], [15, 18], [15, 20]],
  ],
  landmarks: [[27, 17, 'iceSpire'], [2, 17, 'iceSpire']],
  waves: rimeveilWaves,
  startGold: 640,
  startLives: 20,
  startShards: 5,
  intro: 'Three columns come off the north ice at once, and every one of them crosses the crevasses on a bridge you cannot build on. The chill of the aurora slows them - call waves into it.',
}

const stormcrownWaves: WaveDef[] = [
  { groups: [...gates([0, 2], 'husk', 5, 1.5, 0, 2), g('husk', 4, 1.5, 4, 1)] },
  { groups: [g('sprinter', 6, 1.2, 0, 1), ...gates([0, 2], 'shield', 2, 2.4, 3, 2)] },
  { groups: [...gates([0, 1, 2], 'husk', 5, 1.2, 0, 2), g('acolyte', 2, 2.6, 6, 1)] },
  { groups: [g('gargoyle', 4, 1.6, 0, 1), g('shield', 3, 2.2, 2), g('sprinter', 5, 1.2, 4, 2)] },
  { surge: true, groups: [...gates([0, 1, 2], 'shield', 2, 2.2, 0, 2), g('shardback', 2, 5, 8, 1)] },
  { groups: [g('brute', 1, 1, 0, 1), g('warlock', 2, 2.8, 2), g('husk', 10, 1.0, 4, 2)] },
  { groups: [g('mistwalker', 5, 1.4, 0, 2), g('acolyte', 3, 2.4, 2, 1), g('spiderling', 12, 0.55, 5)] },
  { groups: [g('hexling', 1, 1, 3, 1), ...gates([0, 2], 'shield', 4, 1.7, 0, 3), g('shardback', 2, 5, 10, 1)] },
  { surge: true, groups: [...gates([0, 1, 2], 'gargoyle', 4, 1.3, 0, 2), g('brute', 1, 1, 8, 2)] },
  { groups: [g('wardbearer', 1, 1, 2, 1), g('shield', 6, 1.6, 0, 1), g('warlock', 3, 2.4, 4), g('sprinter', 6, 1.1, 6, 2)] },
  { groups: [g('broodmother', 1, 1, 0, 2), g('mistwalker', 7, 1.2, 2), g('acolyte', 3, 2.2, 6, 1)] },
  { surge: true, groups: [g('brute', 2, 7, 0, 1), ...gates([0, 2], 'hexling', 1, 1, 4, 3), g('shield', 8, 1.4, 2, 1)] },
  { groups: [g('riftherald', 1, 1, 3, 1), g('gargoyle', 8, 1.2, 0, 2), g('warlock', 4, 2.2, 5), g('shardback', 2, 5, 10, 2)] },
  { groups: [g('juggernaut', 1, 1, 6, 1), ...gates([0, 2], 'shield', 4, 1.6, 0, 3)], breakAfter: 30 },
  { groups: [...gates([0, 1, 2], 'mistwalker', 4, 1.1, 0, 2), g('wardbearer', 1, 1, 6, 2)] },
  { surge: true, groups: [g('brute', 2, 7, 0, 1), g('acolyte', 3, 2.2, 2, 2), g('spiderling', 10, 0.55, 4), g('shardback', 2, 5, 12, 1)] },
  { groups: [g('riftherald', 2, 9, 0, 2), g('hexling', 2, 6, 3, 1), g('shield', 10, 1.3, 5)] },
  { groups: [...gates([0, 1, 2], 'warlock', 3, 2.0, 0, 2), g('gargoyle', 10, 1.0, 6, 1)] },
  { surge: true, groups: [g('wardbearer', 2, 8, 0, 1), g('broodmother', 2, 8, 2, 2), g('mistwalker', 8, 1.0, 4), g('shardback', 2, 5, 12, 1)] },
  { groups: [g('veilqueen', 1, 1, 6, 1), ...gates([0, 2], 'brute', 2, 7, 0, 3), g('acolyte', 4, 1.9, 8, 1)], breakAfter: 30 },
  { groups: [...gates([0, 1, 2], 'shield', 6, 1.2, 0, 2), g('riftherald', 2, 8, 6, 1)] },
  { surge: true, groups: [g('juggernaut', 1, 1, 5, 2), g('hexling', 3, 5, 0, 1), g('warlock', 5, 1.9, 3), g('gargoyle', 10, 1.0, 7, 1)] },
  { groups: [...gates([0, 1, 2], 'mistwalker', 6, 0.95, 0, 2), g('wardbearer', 2, 8, 6, 1), g('shardback', 3, 4, 10, 2)] },
  { groups: [g('brute', 3, 6, 0, 1), g('broodmother', 2, 8, 2, 2), g('acolyte', 5, 1.8, 4), g('sprinter', 14, 0.7, 8, 1)] },
  { surge: true, groups: [g('riftherald', 2, 8, 0, 1), ...gates([0, 2], 'warlock', 4, 1.8, 2, 3), g('gargoyle', 12, 0.9, 8, 1)] },
  { groups: [g('juggernaut', 1, 1, 4), g('juggernaut', 1, 1, 10, 2), ...gates([0, 1, 2], 'shield', 6, 1.1, 0, 2), g('hexling', 2, 6, 8, 1)], breakAfter: 30 },
  { surge: true, groups: [...gates([0, 1, 2], 'brute', 2, 6, 0, 2), g('wardbearer', 2, 8, 4, 1), g('mistwalker', 10, 0.85, 6)] },
  { groups: [g('veilregent', 1, 1, 8, 1), ...gates([0, 2], 'riftwing', 5, 1.2, 0, 3), g('warlock', 5, 1.8, 6, 1), g('shield', 12, 1.05, 12, 2)] },
]

export const stormcrownLevel: LevelDef = {
  id: 'stormcrown',
  name: 'Stormcrown Citadel',
  subtitle: 'Three roads up the walls',
  theme: 'storm',
  seed: 1621,
  frontier: { tier: 'hard', feature: 'Every road storms two walls to the citadel' },
  ...grid('stormcrown', [
    '##..............aaaaaaaaaaaaaa##',
    '#....o....o...aaAaaaaaAaaaaaaaa#',
    '..............aaaaaaaaaaaaaaaaaa',
    '=====x==============aaaaaaaaaaaa',
    '..............aaaaa=aaaaaaaaaaaa',
    '............~~aaaaa=aaaabbbbbbba',
    '...o..o..o..w~aaAaaxaAabbBbbbBbb',
    '............~~aaaaa=aaabbbbbbbbb',
    '............~~aaaAa=========bbbb',
    '..............aaaaaaaaabbbb=bbbb',
    '====x=======================bbBb',
    '..............aaaaaaaaabbbb=bbbb',
    '............~~aaaAa=========bbbb',
    '...o..o..o..~~aaaaa=aaabbBbbbBbb',
    '............~waaAaaxaAaabbbbbbba',
    '............~~aaaaa=aaaaaaaaaaaa',
    '=====x==============aaaaaaaaaaaa',
    '..............aaaaaaaaaaaaaaaaaa',
    '#....o....o...aaAaaaaaAaaaaaaaa#',
    '##..............aaaaaaaaaaaaaa##',
  ], { a: 0.7, b: 1.4 }),
  lanes: [
    [[0, 3], [11, 3], [14, 3, 0.7], [19, 3, 0.7], [19, 8, 0.7], [20, 8, 0.7], [23, 8, 1.4], [27, 8, 1.4], [27, 10, 1.4]],
    [[0, 10], [8, 10], [14, 10, 0.7], [20, 10, 0.7], [23, 10, 1.4], [27, 10, 1.4]],
    [[0, 16], [11, 16], [14, 16, 0.7], [19, 16, 0.7], [19, 12, 0.7], [20, 12, 0.7], [23, 12, 1.4], [27, 12, 1.4], [27, 10, 1.4]],
  ],
  landmarks: [[29, 2, 'stormSpire'], [29, 17, 'stormSpire']],
  waves: stormcrownWaves,
  startGold: 700,
  startLives: 20,
  startShards: 5,
  intro: 'The storm rolls in over three roads at once. Each one climbs the outer wall, then the citadel wall, to the keep. From the walls you see the whole field; from the field, you see only the foot of the wall.',
}

const duskwreathWaves: WaveDef[] = [
  { groups: gates([0, 1, 2, 3], 'husk', 3, 1.6, 0, 2) },
  { groups: [...gates([0, 1], 'sprinter', 4, 1.3, 0, 2), ...gates([2, 3], 'husk', 4, 1.4, 3, 2)] },
  { groups: [...gates([0, 1, 2, 3], 'shield', 2, 2.4, 0, 2), g('gargoyle', 2, 1.6, 6, 2)] },
  { groups: [g('acolyte', 2, 2.6, 0, 1), g('mistwalker', 3, 1.6, 2, 3), ...gates([0, 2], 'husk', 5, 1.1, 4, 2)] },
  { groups: [...gates([0, 2], 'gargoyle', 2, 1.6, 0, 3), g('shardback', 1, 1, 8, 1)] },
  { surge: true, groups: [g('spiderling', 8, 0.6, 0, 2), g('broodmother', 1, 1, 4, 3), g('riftwing', 1, 1, 6, 0)] },
  { groups: [...gates([1, 3], 'warlock', 2, 2.8, 0, 3), ...gates([0, 2], 'shield', 3, 1.9, 2, 2)] },
  { groups: [g('brute', 1, 1, 0, 0), g('mistwalker', 3, 1.5, 2, 1), g('sprinter', 5, 1.2, 4, 2), g('shardback', 1, 1, 9, 3)] },
  { surge: true, groups: [...gates([0, 1, 2, 3], 'mistwalker', 2, 1.4, 0, 2), g('hexling', 1, 1, 6, 1)] },
  { groups: [g('riftwing', 2, 2.0, 0, 3), g('acolyte', 2, 2.6, 2, 0), ...gates([1, 2], 'shield', 3, 1.8, 4, 2)] },
  { groups: [g('wardbearer', 1, 1, 2, 2), ...gates([0, 1, 2, 3], 'husk', 5, 1.0, 0, 1.5), g('shardback', 2, 5, 10, 0)] },
  { surge: true, groups: [g('broodmother', 1, 1, 0, 1), g('gargoyle', 8, 1.2, 2, 3), g('warlock', 3, 2.4, 5, 0)] },
  { groups: [...gates([0, 2], 'brute', 1, 1, 0, 4), ...gates([1, 3], 'mistwalker', 5, 1.2, 2, 2)] },
  { groups: [g('riftherald', 1, 1, 3, 0), g('riftwing', 4, 1.5, 0, 1), g('hexling', 1, 1, 5, 3), g('shardback', 2, 5, 10, 2)] },
  { groups: [g('hollowking', 1, 1, 6, 2), ...gates([0, 1, 3], 'gargoyle', 4, 1.2, 0, 2)], breakAfter: 30 },
  { surge: true, groups: [...gates([0, 1, 2, 3], 'shield', 4, 1.4, 0, 2), g('acolyte', 4, 2.1, 8, 1)] },
  { groups: [g('wardbearer', 1, 1, 0, 3), g('warlock', 4, 2.2, 2, 0), g('spiderling', 10, 0.55, 4, 1), g('shardback', 2, 5, 12, 2)] },
  { groups: [...gates([1, 3], 'brute', 2, 7, 0, 3), ...gates([0, 2], 'riftwing', 3, 1.4, 2, 2)] },
  { surge: true, groups: [...gates([0, 1, 2, 3], 'mistwalker', 5, 1.0, 0, 2), g('hexling', 2, 6, 6, 0)] },
  { groups: [g('riftherald', 2, 9, 0, 1), g('broodmother', 2, 8, 2, 2), g('acolyte', 4, 2.0, 4, 3), g('gargoyle', 10, 0.95, 6, 0)] },
  { groups: [...gates([0, 2], 'wardbearer', 1, 1, 0, 4), ...gates([1, 3], 'shield', 7, 1.25, 2, 2), g('shardback', 3, 4, 10, 0)] },
  { surge: true, groups: [...gates([0, 1, 2, 3], 'riftwing', 3, 1.25, 0, 2), g('brute', 2, 6, 6, 2)] },
  { groups: [g('warlock', 6, 1.9, 0, 3), g('mistwalker', 10, 0.9, 2, 0), g('hexling', 2, 5, 5, 1), g('shield', 10, 1.15, 8, 2)] },
  { groups: [g('juggernaut', 1, 1, 6, 1), ...gates([0, 2, 3], 'acolyte', 3, 2.0, 0, 3), g('gargoyle', 12, 0.85, 8, 2)], breakAfter: 30 },
  { surge: true, groups: [...gates([0, 1, 2, 3], 'brute', 1, 1, 0, 3), ...gates([0, 2], 'mistwalker', 7, 0.9, 4, 2)] },
  { groups: [g('riftherald', 2, 8, 0, 2), g('wardbearer', 2, 8, 3, 3), g('broodmother', 2, 8, 5, 0), g('shardback', 3, 4, 12, 1)] },
  { groups: [...gates([0, 1, 2, 3], 'warlock', 3, 1.8, 0, 2), g('riftwing', 6, 1.2, 6, 3), g('shield', 12, 1.05, 10, 1)] },
  { surge: true, groups: [g('juggernaut', 1, 1, 4, 3), ...gates([0, 1, 2], 'mistwalker', 7, 0.85, 0, 2), g('hexling', 3, 5, 8, 3)] },
  { groups: [g('veilqueen', 1, 1, 4, 0), ...gates([1, 2, 3], 'gargoyle', 7, 0.95, 0, 2), g('acolyte', 5, 1.8, 10, 2)], breakAfter: 30 },
  { groups: [g('veilregent', 1, 1, 8, 0), ...gates([0, 1, 2, 3], 'shield', 5, 1.2, 0, 2), ...gates([1, 2], 'riftwing', 3, 1.3, 10, 3)] },
]

export const duskwreathLevel: LevelDef = {
  id: 'duskwreath',
  name: 'Duskwreath Ring',
  subtitle: 'Four gates around a black sun',
  theme: 'eclipse',
  seed: 4861,
  frontier: { tier: 'hard', feature: 'Four gates circle a chasm; two bridges reach the keep' },
  ...grid('duskwreath', [
    '###########..........###########',
    '########................########',
    '######...o............o...######',
    '#####......................#####',
    '####======x==========x======####',
    '###.=..........=...........=.###',
    '##..=....o..o..=...o..o....=..##',
    '#...=.o....####%#####....o.=...#',
    '#...=.....#####%######.....=...#',
    '.====....####bb=bbb####....====.',
    '........####bBb=bbbb####........',
    '..o...o.####bbb==bbb####.o...o..',
    '........####bbbb=bbb####........',
    '........####bbbb=bBb####........',
    '.====....####bbb=bb####....====.',
    '#...=.....######%#####.....=...#',
    '#...=.o....#####%####....o.=...#',
    '##..=....o..o...=..o..o....=..##',
    '###.=...........=..........=.###',
    '####======x==========x======####',
    '#####......................#####',
    '######...o............o...######',
    '########................########',
    '###########..........###########',
  ], { b: 1.2 }),
  lanes: [
    [[1, 9], [4, 9], [4, 4], [15, 4], [15, 5], [15, 9, 1.2], [15, 11, 1.2]],
    [[30, 14], [27, 14], [27, 19], [16, 19], [16, 18], [16, 14, 1.2], [16, 11, 1.2], [15, 11, 1.2]],
    [[30, 9], [27, 9], [27, 4], [15, 4], [15, 5], [15, 9, 1.2], [15, 11, 1.2]],
    [[1, 14], [4, 14], [4, 19], [16, 19], [16, 18], [16, 14, 1.2], [16, 11, 1.2], [15, 11, 1.2]],
  ],
  landmarks: [[15, 21, 'eclipseAltar'], [2, 6, 'monolith']],
  waves: duskwreathWaves,
  startGold: 880,
  startLives: 20,
  startShards: 5,
  intro: 'The sun has gone out. Four gates open on the rim of the ring, and every column crosses the chasm on one of two bridges to reach the keep in the middle. Nothing about this is fair.',
}

/** in the order the Frontier screen lists them: gentlest first */
export const frontierLevels: LevelDef[] = [
  lanternbloomLevel, cloudstepLevel, dunewakeLevel,
  serpentLevel, glimmerdeepLevel, starfallLevel, coralspireLevel,
  rimeveilLevel, stormcrownLevel, duskwreathLevel,
]

export { FRONTIER_TIERS } from './frontierIndex.ts'

registerBoards(frontierLevels)
