import { test, expect, bootToMenu, startBattle } from './fixtures.ts'
import type { Game } from '../../src/game/game.ts'
async function openHold(page: import('@playwright/test').Page) {
  await page.getByRole('button', { name: /Your Hold/ }).click()
  await expect(page.locator('.hold-panel h2')).toBeVisible()
}

test('Hold editing saves, cancels, stores, places and survives reload', async ({ page, consoleErrors }) => {
  await bootToMenu(page); await openHold(page)
  await page.getByRole('button', { name: 'Customize', exact: true }).click()
  await page.getByLabel('Hold name').fill('Cedar Watch')
  await page.locator('.hold-toolbar').getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.locator('.hold-heading h1')).toHaveText('Cedar Watch')
  await page.getByRole('button', { name: 'Collection', exact: true }).click()
  const pine = page.locator('.hold-reward').filter({ has: page.getByRole('heading', { name: 'Courtyard Pine 1', exact: true }) })
  await pine.getByRole('button', { name: 'Select', exact: true }).click()
  await page.getByRole('button', { name: 'Store', exact: true }).click()
  await page.locator('.hold-toolbar').getByRole('button', { name: 'Save', exact: true }).click()
  await page.reload(); await openHold(page)
  await expect(page.locator('.hold-heading h1')).toHaveText('Cedar Watch')
  await page.getByRole('button', { name: 'Collection', exact: true }).click()
  await pine.getByRole('button', { name: 'Place', exact: true }).click()
  await page.keyboard.press('ArrowRight'); await page.keyboard.press('r'); await page.keyboard.press('Enter')
  await page.locator('.hold-toolbar').getByRole('button', { name: 'Save', exact: true }).click()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('blockhold.save.v1')!).hold)
  expect(saved.stored).not.toContain('tree:0')
  expect(saved.placements.find((p: { id: string }) => p.id === 'tree:0')).toMatchObject({ x: 1, z: 0, r: 1 })
  await page.getByRole('button', { name: 'Customize', exact: true }).click()
  // Deselect an inspected object to reveal style controls.
  const deselect = page.getByRole('button', { name: 'Deselect piece' }); if (await deselect.isVisible()) await deselect.click()
  await page.getByLabel('Hold name').fill('Discard me')
  await page.locator('.hold-toolbar').getByRole('button', { name: 'Cancel edits' }).click()
  await page.getByRole('button', { name: 'Discard edits', exact: true }).click()
  await expect(page.locator('.hold-heading h1')).toHaveText('Cedar Watch')
  expect(consoleErrors).toEqual([])
})

test('failed Hold storage keeps the draft open and exports without claiming success', async ({ page, consoleErrors }) => {
  await bootToMenu(page); await openHold(page)
  await page.getByRole('button', { name: 'Customize', exact: true }).click()
  await page.getByLabel('Hold name').fill('Unsaved Watch')
  await page.evaluate(() => { const old = Storage.prototype.setItem; Storage.prototype.setItem = function(k, v) { if (k === 'blockhold.save.v1') throw new DOMException('Quota exceeded'); old.call(this, k, v) } })
  await page.locator('.hold-toolbar').getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('draft is still open')
  await expect(page.getByRole('button', { name: 'Export draft backup' })).toBeVisible()
  expect(await page.evaluate(() => (window.vg.game as unknown as Game).save.hold?.name)).not.toBe('Unsaved Watch')
  expect(consoleErrors).toEqual([])
})

test('read-only visits do not overwrite the visitor or a saved battle', async ({ page, context, consoleErrors }) => {
  await bootToMenu(page)
  await startBattle(page)
  await page.evaluate(() => { const game = window.vg.game as unknown as Game; game.saveSession(); (window.vg.hud as { onHome: () => void }).onHome() })
  const battle = await page.evaluate(() => localStorage.getItem('blockhold.session.v1'))
  expect(battle).toBeTruthy()
  await openHold(page)
  await page.getByRole('button', { name: 'Customize', exact: true }).click(); await page.getByLabel('Hold name').fill('Visit me')
  await page.locator('.hold-toolbar').getByRole('button', { name: 'Save', exact: true }).click()
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.getByRole('button', { name: 'Share', exact: true }).click()
  await page.getByRole('button', { name: 'Copy visit link' }).click()
  const link = await page.evaluate(() => navigator.clipboard.readText())
  expect(link).toContain('#visit=')
  const before = await page.evaluate(() => localStorage.getItem('blockhold.save.v1'))
  await page.goto(link)
  await expect(page.getByText('Visiting a shared Hold')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Customize', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'My Hold', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Customize', exact: true })).toBeVisible()
  expect(page.url()).not.toContain('visit=')
  await page.reload(); await openHold(page)
  await expect(page.getByRole('button', { name: 'Customize', exact: true })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('blockhold.save.v1'))).toBe(before)
  expect(await page.evaluate(() => localStorage.getItem('blockhold.session.v1'))).toBe(battle)
  await page.goto('/#visit=invalid!')
  await expect(page.getByText('This visit link could not be opened')).toBeVisible()
  expect(consoleErrors).toEqual([])
})

test('touch Hold selection toggles, drags do not place and repeated exits release owned resources', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  const page = await context.newPage(); await page.goto('http://127.0.0.1:4173/'); await page.waitForFunction(() => window.vg)
  await openHold(page)
  await page.getByRole('button', { name: 'Collection', exact: true }).tap()
  await page.locator('.hold-reward').filter({ hasText: 'Courtyard Pine 1' }).getByRole('button', { name: 'Select', exact: true }).tap()
  await page.getByRole('button', { name: 'Deselect piece' }).tap()
  await expect(page.getByRole('button', { name: 'Deselect piece' })).toHaveCount(0)
  const spot = await page.evaluate(() => {
    const game = window.vg.game as unknown as Game
    let found: { x: number, y: number } | null = null
    game.engine.scene.getObjectByName('your-hold')!.traverse(o => { if (o.userData.holdId === 'tree:0') found = game.projectToScreen(o.position.x, .8, o.position.z) })
    return found!
  })
  await page.touchscreen.tap(spot.x, spot.y)
  await expect(page.getByRole('button', { name: 'Deselect piece' })).toBeVisible()
  await page.touchscreen.tap(spot.x, spot.y)
  await expect(page.getByRole('button', { name: 'Deselect piece' })).toHaveCount(0)
  await page.touchscreen.tap(spot.x, spot.y)
  await page.getByRole('button', { name: 'Move', exact: true }).tap()
  const hint = await page.locator('.hold-panel p').textContent()
  const cdp = await context.newCDPSession(page)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: spot.x, y: spot.y, id: 1 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: spot.x + 60, y: spot.y + 20, id: 1 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(page.locator('.hold-panel p')).toHaveText(hint!)
  await page.getByRole('button', { name: 'Cancel', exact: true }).tap()
  const measurements: { geometries: number, children: number }[] = []
  for (let i = 0; i < 5; i++) {
    await page.getByRole('button', { name: '← Home', exact: true }).tap()
    await openHold(page)
    measurements.push(await page.evaluate(() => { const e = (window.vg.game as unknown as Game).engine; return { geometries: e.renderer.info.memory.geometries, children: e.scene.children.length } }))
  }
  expect(measurements.slice(1).every(m => m.geometries <= measurements[0].geometries + 1 && m.children === measurements[0].children)).toBe(true)
  await page.getByRole('button', { name: 'Customize', exact: true }).tap()
  await expect(page.locator('.hold-toolbar').getByRole('button', { name: 'Save', exact: true })).toBeInViewport()
  await page.setViewportSize({ width: 844, height: 390 })
  await expect(page.locator('.hold-toolbar').getByRole('button', { name: 'Cancel edits' })).toBeInViewport()
  await page.screenshot({ path: 'tests/smoke/output/hold-touch-landscape.png' })
  await context.close()
})
